# 配置到Nacos配置中心区
spring:
  boot:
    admin:
      client:
        url: http://localhost:8110/ # spring boot admin server 地址
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # # 启用服务发现，开启动态路由
          lower-case-service-id: true # 开启服务名称小写
      routes:
        - id: mall-admin # mall-admin模块路由
          uri: lb://mall-admin # 占位符
          predicates: # 断言
            - Path=/mall-admin/**
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 8 # 最大活跃连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: -1 # 获取连接的最大等待时间（-1表示无限等待）
        shutdown-timeout: 2000 # 连接池关闭时的超时时间（毫秒）

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露给监控全部接口

secure:
  ignore:
    urls: #配置白名单路径
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/mall-auth/oauth/token" # 获取token
      - "/mall-auth/rsa/publicKey" # 获取认证公钥
      - "/mall-admin/admin/login" # 后台登录
      - "/mall-admin/admin/register" # 后台注册