# 配置到Nacos配置中心区
spring:
  boot:
    admin:
      client:
        url: http://localhost:8110/ # spring boot admin server 地址
  security:
    user:
      name: songbaicheng # 默认用户名
      password: songbaicheng # 默认用户密码
      roles: # 默认用户身份
        - admin

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露给监控全部接口