# 配置到Nacos配置中心区
spring:
  boot:
    admin:
      client:
        url: http://localhost:8110/ # spring boot admin server 地址
  datasource:
    url: jdbc:mysql://localhost:3306/mall-auth # 数据库
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    username: root # 账户
    password: songbaicheng # 密码
  security:
    oauth2:
      clients:
        use-current-uri: true
        registration:
          mall-web:
            client-id: mall-web
            client-secret: '{bcrypt}$2a$10$g09oT29NxLtpF3zb70o3v.gFS/cNCFCe4wiYe5E2JsP.2l4gquHXa'
            authorization-grant-type: client_credentials,urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: all
            redirect-uri: https://www.baidu.com/index.htm
            allowFormAuthenticationForClients: true
#        provider:
#          mall-web:
#            authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize
#            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token

logging:
  level:
    com.mall.auth: info
  file:
    name: /Users/songbaicheng/logs/cloud-mall/mall-auth/mall-auth.log

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露给监控全部接口

jwt:
  secret: 650e387e-d8ba-43cd-9237-a9274a675f7b # 与HMAC-SHA算法一起使用的密钥必须具有>=256位的大小
  expiration: 3600 # 设