spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-admin # 数据库
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    username: root # 账户
    password: songbaicheng # 密码

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # mapper映射文件位置
  type-aliases-package: com/mall/admin/entity # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true # 驼峰转下划线
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印sql
  global-config:
    banner: false # 关闭mybatis-plus启动logo
    db-config:
      logic-delete-field: deleted # 逻辑删除字段
      logic-delete-value: 1 # 删除状态
      logic-not-delete-value: 0 # 未删除状态