spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-admin # 数据库
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    username: root # 账户
    password: songbaicheng # 密码

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰转下划线
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台sql展示
  global-config:
    banner: false # 关闭mybatis-plus启动logo