
server:
  port: 8080 # 应用服务 WEB 访问端口

spring:
  application:
    name: mall-admin # 服务注册名称
  cloud:
    nacos:
      config:
        server-addr: localhost:8848 # 服务注册地址
        username: nacos # 账号
        password: nacos # 密码
      discovery:
        namespace: 23e970ba-46e6-42b7-bacf-3bf8e668cbb8 # 命名空间ID
        group: CLOUD_MALL_GROUP # 分组名称